name: Test gradlew permissions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files before changing permissions
        run: ls -la

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: List files after changing permissions
        run: ls -la

      - name: Run gradlew
        run: ./gradlew --version
